language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

sudo: false

services:
  - docker

install: true

script: "mvn clean dependency:list test -Pall-dbs -Dsort -U"
