language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - PROFILE=ci
    - PROFILE=spring5-next
    - PROFILE=solr7-next
    - PROFILE=solr8-next

addons:
  apt:
    packages:
    - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

sudo: false

install: true

script: "mvn clean test -P${PROFILE}"