language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - PROFILE=spring5-next

addons:
  apt:
    packages:
    - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

sudo: false

install: true

script: travis_wait make test SPRING_PROFILE=${PROFILE}
